# PS C:\Users\vedan\OneDrive\Desktop\Coding\Python\Python-learning\chapter 13> pip freeze > requirements.txt
# PS C:\Users\vedan\OneDrive\Desktop\Coding\Python\Python-learning\chapter 13> virtualenv Rajeshenv
# created virtual environment CPython3.13.0.final.0-64 in 1518ms
#   creator CPython3Windows(dest=C:\Users\vedan\OneDrive\Desktop\Coding\Python\Python-learning\chapter 13\Rajeshenv, clear=False, no_vcs_ignore=False, global=False)
#   seeder FromAppData(download=False, pip=bundle, via=copy, app_data_dir=C:\Users\vedan\AppData\Local\pypa\virtualenv)
#     added seed packages: pip==24.3.1
#   activators BashActivator,BatchActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
# PS C:\Users\vedan\OneDrive\Desktop\Coding\Python\Python-learning\chapter 13> .\Rajeshenv\Scripts\activate.ps1
# (Rajeshenv) PS C:\Users\vedan\OneDrive\Desktop\Coding\Python\Python-learning\chapter 13> pip install -r requirements.txt
# Collecting art==6.4 (from -r requirements.txt (line 1))
#   Using cached art-6.4-py3-none-any.whl.metadata (71 kB)
# Collecting blinker==1.9.0 (from -r requirements.txt (line 2))
#   Using cached blinker-1.9.0-py3-none-any.whl.metadata (1.6 kB)
# Collecting click==8.1.7 (from -r requirements.txt (line 3))
#   Using cached click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
# Collecting colorama==0.4.6 (from -r requirements.txt (line 4))
#   Using cached colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
# Collecting comtypes==1.4.8 (from -r requirements.txt (line 5))
#   Using cached comtypes-1.4.8-py3-none-any.whl.metadata (7.1 kB)
# Collecting distlib==0.3.9 (from -r requirements.txt (line 6))
#   Using cached distlib-0.3.9-py2.py3-none-any.whl.metadata (5.2 kB)
# Collecting emoji==2.14.0 (from -r requirements.txt (line 7))
#   Using cached emoji-2.14.0-py3-none-any.whl.metadata (5.7 kB)
# Collecting filelock==3.16.1 (from -r requirements.txt (line 8))
#   Using cached filelock-3.16.1-py3-none-any.whl.metadata (2.9 kB)
# Collecting Flask==3.1.0 (from -r requirements.txt (line 9))
#   Using cached flask-3.1.0-py3-none-any.whl.metadata (2.7 kB)
# Collecting itsdangerous==2.2.0 (from -r requirements.txt (line 10))
#   Using cached itsdangerous-2.2.0-py3-none-any.whl.metadata (1.9 kB)
# Collecting Jinja2==3.1.4 (from -r requirements.txt (line 11))
#   Using cached jinja2-3.1.4-py3-none-any.whl.metadata (2.6 kB)
# Collecting MarkupSafe==3.0.2 (from -r requirements.txt (line 12))
#   Using cached MarkupSafe-3.0.2-cp313-cp313-win_amd64.whl.metadata (4.1 kB)
# Collecting numpy==2.2.1 (from -r requirements.txt (line 13))
#   Using cached numpy-2.2.1-cp313-cp313-win_amd64.whl.metadata (60 kB)
# Collecting pandas==2.2.3 (from -r requirements.txt (line 14))
#   Using cached pandas-2.2.3-cp313-cp313-win_amd64.whl.metadata (19 kB)
# Collecting platformdirs==4.3.6 (from -r requirements.txt (line 15))
#   Using cached platformdirs-4.3.6-py3-none-any.whl.metadata (11 kB)
# Collecting pyjokes==0.8.3 (from -r requirements.txt (line 16))
#   Using cached pyjokes-0.8.3-py3-none-any.whl.metadata (3.4 kB)
# Collecting pypiwin32==223 (from -r requirements.txt (line 17))
#   Using cached pypiwin32-223-py3-none-any.whl.metadata (236 bytes)
# Collecting python-dateutil==2.9.0.post0 (from -r requirements.txt (line 18))
#   Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
# Collecting pyttsx3==2.98 (from -r requirements.txt (line 19))
#   Using cached pyttsx3-2.98-py3-none-any.whl.metadata (3.8 kB)
# Collecting pytz==2024.2 (from -r requirements.txt (line 20))
#   Using cached pytz-2024.2-py2.py3-none-any.whl.metadata (22 kB)
# Collecting pywin32==308 (from -r requirements.txt (line 21))
#   Using cached pywin32-308-cp313-cp313-win_amd64.whl.metadata (8.3 kB)
# Collecting six==1.17.0 (from -r requirements.txt (line 22))
#   Using cached six-1.17.0-py2.py3-none-any.whl.metadata (1.7 kB)
# Collecting typing==3.7.4.3 (from -r requirements.txt (line 23))
#   Using cached typing-3.7.4.3-py3-none-any.whl
# Collecting tzdata==2024.2 (from -r requirements.txt (line 24))
#   Using cached tzdata-2024.2-py2.py3-none-any.whl.metadata (1.4 kB)
# Collecting virtualenv==20.28.1 (from -r requirements.txt (line 25))
#   Using cached virtualenv-20.28.1-py3-none-any.whl.metadata (4.5 kB)
# Collecting Werkzeug==3.1.3 (from -r requirements.txt (line 26))
#   Using cached werkzeug-3.1.3-py3-none-any.whl.metadata (3.7 kB)
# Using cached art-6.4-py3-none-any.whl (608 kB)
# Using cached blinker-1.9.0-py3-none-any.whl (8.5 kB)
# Using cached click-8.1.7-py3-none-any.whl (97 kB)
# Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
# Using cached comtypes-1.4.8-py3-none-any.whl (229 kB)
# Using cached distlib-0.3.9-py2.py3-none-any.whl (468 kB)
# Using cached emoji-2.14.0-py3-none-any.whl (586 kB)
# Using cached filelock-3.16.1-py3-none-any.whl (16 kB)
# Using cached flask-3.1.0-py3-none-any.whl (102 kB)
# Using cached itsdangerous-2.2.0-py3-none-any.whl (16 kB)
# Using cached jinja2-3.1.4-py3-none-any.whl (133 kB)
# Using cached MarkupSafe-3.0.2-cp313-cp313-win_amd64.whl (15 kB)
# Using cached numpy-2.2.1-cp313-cp313-win_amd64.whl (12.6 MB)
# Using cached pandas-2.2.3-cp313-cp313-win_amd64.whl (11.5 MB)
# Using cached platformdirs-4.3.6-py3-none-any.whl (18 kB)
# Using cached pyjokes-0.8.3-py3-none-any.whl (47 kB)
# Using cached pypiwin32-223-py3-none-any.whl (1.7 kB)
# Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
# Using cached pyttsx3-2.98-py3-none-any.whl (34 kB)
# Using cached pytz-2024.2-py2.py3-none-any.whl (508 kB)
# Using cached pywin32-308-cp313-cp313-win_amd64.whl (6.5 MB)
# Using cached six-1.17.0-py2.py3-none-any.whl (11 kB)
# Using cached tzdata-2024.2-py2.py3-none-any.whl (346 kB)
# Using cached virtualenv-20.28.1-py3-none-any.whl (4.3 MB)
# Using cached werkzeug-3.1.3-py3-none-any.whl (224 kB)
# Installing collected packages: pywin32, pytz, distlib, tzdata, typing, six, pypiwin32, pyjokes, platformdirs, numpy, MarkupSafe, itsdangerous, filelock, emoji, comtypes, colorama, blinker, art, Werkzeug, virtualenv, pyttsx3, python-dateutil, Jinja2, click, pandas, Flask
# ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Users\\vedan\\OneDrive\\Desktop\\Coding\\Python\\Python-learning\\chapter 13\\Rajeshenv\\Lib\\site-packages\\distlib-0.3.9.dist-info\\RECORD_pdmjm9k.tmp' -> 'C:\\Users\\vedan\\OneDrive\\Desktop\\Coding\\Python\\Python-learning\\chapter 13\\Rajeshenv\\Lib\\site-packages\\distlib-0.3.9.dist-info\\RECORD'
# Check the permissions.