e = set()
e1 = input ("enter the no. 1 :")
e.add(int(e1)) #to take the input in integer value
e1 = input ("enter the no. 2 :")
e.add(int(e1))
e1 = input ("enter the no. 3 :")
e.add(int(e1))
e1 = input ("enter the no. 4 :")
e.add(int(e1))
e1 = input ("enter the no. 5 :")
e.add(int(e1))
e1 = input ("enter the no. 6 :")
e.add(int(e1))
e1 = input ("enter the no. 7 :")
e.add(int(e1))
e1 = input ("enter the no. 8 :")
e.add(int(e1))

print(e)