e = set()
e1 = input ("enter the no. 1 :")
e.add(e1)
e1 = input ("enter the no. 2 :")
e.add(e1)
e1 = input ("enter the no. 3 :")
e.add(e1)
e1 = input ("enter the no. 4 :")
e.add(e1)
e1 = input ("enter the no. 5 :")
e.add(e1)
e1 = input ("enter the no. 6 :")
e.add(e1)
e1 = input ("enter the no. 7 :")
e.add(e1)
e1 = input ("enter the no. 8 :")
e.add(e1)

print(e)